# -*- coding: utf-8 -*-
"""speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcal9TmrUwcLxI9_Rgzli1cODgX5enFv
"""

!pip install deep-translator gTTs

from deep_translator import GoogleTranslator
def translate_text(text_to_translate,*target_language):
  for i in target_language:
    translator=GoogleTranslator(source="auto",target=i)
    translated_text=translator.translate(text_to_translate)
    print(translated_text)

translate_text("hi how are you","en","hi")

from gtts import gTTS
import os
def text_to_speech(text,language="en"):
  tts=gTTS(text=text,lang=language,slow=False)
  tts.save("output.mp3")
  os.system("start output.mp3")

input_text="hello! how are you?"

text_to_speech(input_text,"fr")

import requests
import json
def

